version: '3'

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8080"
    env_file:
      - ./.env
    volumes:
     - ../certs/:${CERT_PATH}
  
  db:
    container_name: 'timetable_db'
    image: 'postgres:14'
    restart: always
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
