"""empty message

Revision ID: a3a4a86f1fc0
Revises: 9c16f42e858f
Create Date: 2025-01-06 17:31:25.172242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3a4a86f1fc0'
down_revision = '9c16f42e858f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tg_id', sa.TEXT(), nullable=False),
    sa.Column('degree', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__schedule'))
    )
    op.create_index(op.f('ix__schedule__tg_id'), 'schedule', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__schedule__tg_id'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
